apiVersion: v1
kind: Service
metadata:
  name: tenant-api
  namespace: {{ .Values.tenant | quote }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app: tenant-api
    tenant: {{ .Values.tenant | quote }}
  type: {{ .Values.service.type | default "ClusterIP" | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8080 }}
      targetPort: 8080
